# agent/db_migrations.py
from __future__ import annotations

import os
import sqlite3


def ensure_schema(db_path: str) -> None:
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    con = sqlite3.connect(db_path)
    cur = con.cursor()
    cur.execute(
        """
    CREATE TABLE IF NOT EXISTS pages (
      url TEXT PRIMARY KEY,
      source TEXT,
      title TEXT,
      fetched_at TEXT,
      sha256 TEXT,
      content TEXT,
      text TEXT,
      processed INTEGER DEFAULT 0,
      error TEXT
    );
    """
    )
    cur.execute("CREATE INDEX IF NOT EXISTS idx_pages_fetched_at ON pages(fetched_at);")
    # table for tracking page content changes
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS changes (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          url TEXT,
          changed_at TEXT,
          source TEXT,
          old_sha TEXT,
          new_sha TEXT,
          diff_excerpt TEXT
        );
        """
    )
    cur.execute(
        "CREATE INDEX IF NOT EXISTS idx_changes_changed_at ON changes(changed_at);"
    )

    # table for alerts generated by agent.alerts
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS alerts (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          created_at TEXT,
          level TEXT,
          title TEXT,
          message TEXT,
          context_json TEXT
        );
        """
    )
    cur.execute(
        "CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at);"
    )
    # published_at: article publication date from RSS feeds (NULL for web-search results)
    try:
        cur.execute("ALTER TABLE pages ADD COLUMN published_at TEXT")
        con.commit()
    except sqlite3.OperationalError:
        pass  # column already exists
    con.commit()
    con.close()
